var ENGLISH_WORDS = [
  "Clemson",
  "Paris",
  "Toronto",
  "Shanghai",
  "Beijing",
  "Tallahassee",
  "Nashville",
  "Jackson",
  "Greenville",
  "Seoul",
  "Salt Lake",
  "Columbia",
  "Prague",
  "Berlin",
  "Cozumel",
  "Naples",
  "Hyderabad",
  "Pune",
  "Mumbai",
  "Bangkok",
  "Dubai",
  "Aberdeen", 
  "Abilene", 
  "Akron", 
  "Albany", 
  "Albuquerque", 
  "Alexandria", 
  "Allentown", 
  "Amarillo", 
  "Anaheim", 
  "Anchorage", 
  "Appleton", "Arlington", "Arvada", "Asheville", "Athens", "Atlanta", "Augusta", "Aurora", "Austin", "Bakersfield", "Baltimore", 
  "Barnstable","Beaumont", "Bellevue", "Berkeley", "Bethlehem", "Billings", "Birmingham", "Bloomington", "Boise", "Boston", "Boulder", 
  "Bradenton", "Bremerton", "Bridgeport", "Brighton", "Brownsville", "Bryan", "Buffalo", "Burbank", "Burlington", "Cambridge", "Canton", 
  "Carrollton", "Cary", "Champaign", "Chandler", "Charleston", "Charlotte", "Chattanooga", "Chesapeake", "Chicago", "Cincinnati", 
  "Clarksville", "Clearwater", "Cleveland", "Columbia", "Columbus", "Concord", "Corona", "Dallas", "Danbury", "Davenport","Dayton", 
  "Deltona", 
  "Denton", "Denver","Detroit", "Downey", "Duluth", "Durham", "Elizabeth", "Erie", "Escondido", "Eugene", "Evansville", "Fairfield", 
  "Fargo", "Fayetteville", "Fitchburg", "Flint", "Fontana", "Frederick", "Fremont", "Fresno", "Fullerton", "Gainesville",
  "Indianapolis", "Inglewood", "Irvine", "Irving", "Jackson", "Jacksonville", "Jefferson", "Joliet", "Kailua", "Kalamazoo", "Kaneohe", 
  "Kennewick", "Kenosha", "Killeen", "Kissimmee", "Knoxville", "Lacey", "Lafayette", "Sarasota", "Savannah", "Scottsdale", "Scranton", 
  "Seaside", "Seattle", "Sebastian", "Shreveport", "Spartanburg", "Spokane", "Stamford", "Stockton", "Sunnyvale", "Syracuse", 
  "Tacoma", "Tallahassee", "Tampa", "Temecula", "Tempe", "Thornton", "Toledo", "Topeka", "Torrance", "Trenton", "Tucson", "Tulsa", 
  "Tuscaloosa", "Tyler", "Utica", "Vallejo", "Vancouver", "Victorville", "Visalia", "Waco", "Warren", "Washington", "Waterbury", 
  "Waterloo", "Westminster", "Wichita", "Wilmington", "Winston", "Worcester", "Yakima", "Yonkers", "York", "Youngstown",
  "shreya",
  "nidhi"
].map(v => v.toLowerCase());

function randomWord() {
  return ENGLISH_WORDS[Math.floor(Math.random() * ENGLISH_WORDS.length)];
}

export { randomWord };
